#+title: Automatic speech recognition of swedish text
#+cite_export: csl

* Automatic speech recognition
This is a tensorflow implementation of an automatic speech recognition
(ASR) system. The model uses spectrograms and transformers to predict
characters that occur in sound.

The dataset used here is [[https://commonvoice.mozilla.org/en/datasets][Mozilla Common voice (swedish)]].

** Model description
The model is based on the attention is all you need
tranformer[cite:@vaswani2017attention], with added spectrogram
generation. Spectrograms are split into patches along the time
dimension before being encoded via a convolutional model.

The transformer is tasked with predicting characters from the input
sequence of encoded patches. Predicting characters rather than words
allow a smaller vocabulary and suits the speech recognition task quite
well.

** Example results
In these examples, =_= denotes padding, =<= beginning-of-sentence and =>=
end-of-sentence. The target string is the true spoken sentence for a
certain voice clip.

Since the loss is masked out for padding characters, the model fills
the tokens after the first =>= with random characters.

Epoch 1
#+begin_src text
target:     <vi kan resa dit och gifta oss.>__________________________________________________________________________________
prediction: <det är skar det skon skon det det den det ska skon.>.>.>.>len.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>een.>r.haraenhen>h>>>>>g n   .>.>.>.>.>e.>.

target:     <även jag läste den och fick tillåtelse att göra illustrationer på de breda marginalerna.>________________________
prediction: <det är skar som ston sten som skon skom sten ska skan skon skom skomen.>len.>.>.>.>.>.>en.>.>.>.>.>erer.>.>.>a.>eshenteröraaemhih>hh>>>>g>g c> >  e e e e > 

target:     <låt dem veta att vi vet vad som pågår.>__________________________________________________________________________
prediction: <det är skar star sten som soch skar den sta ska skan som skom somen.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>eeeen.>röraranhehen>h>>>>g c>  >.>.>.>.>e.>e.

target:     <jag ska lära sig att hålla dig tyst, när jag vill sova.>_________________________________________________________
prediction: <det är skar det skon skon den skan den den ska skon.>.>.>llen.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>een.>r.haraenhen>h>>>>>g n   .>.>.>.>.>e.>.
#+end_src


Epoch 20
#+begin_src text
target:     <vi kan resa dit och gifta oss.>__________________________________________________________________________________
prediction: <vi kan resa i vildsaken.>>.>.>>.>.>.>.>.>.>.>.>.>.>elt.>>nås.>>en.>>orenssarnen.>>>aren.>>.>>or.>>>>>.>s>nnnns>>>>>>>nnnnnns>>>>>>>>>nnnnnsssssssssseeeeers>

target:     <även jag läste den och fick tillåtelse att göra illustrationer på de breda marginalerna.>________________________
prediction: <än lade med den och kompenterat att tillämpsamman och resade de till brodsädelar.>ena.>.>.>.>.>.>.>.>.>.>.>na.>e.>a.>.>.>.>eneneeee.>en.>.....>.>.>...ee.>.>

target:     <låt dem veta att vi vet vad som pågår.>__________________________________________________________________________
prediction: <under var det en blick repontionen och såg på honom.>>.>>.>>.>>.>>t.>>t.>>.>>t.>>.>>.>>.>>.>>>.>.>.>.>.>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>.>.>sss.>.>.>.>.>.>.>>>

target:     <jag ska lära sig att hålla dig tyst, när jag vill sova.>_________________________________________________________
prediction: <jag ska göra dit låna gå till stora.>>.>>.>>.>>.>>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>>>>>.>>>>>>>>>>>.>.>.>.....>.>.s...>.>.>
#+end_src

Epoch 45
#+begin_src text
target:     <vi kan resa dit och gifta oss.>__________________________________________________________________________________
prediction: <vi kan resa dit och gifta oss.>>.>>.>>näst.>>.>>.>>>våset.>>.>>g.>>g.>>g.>>.>n.>n.>>.>.>.>.>n.>>.>>.>>.>>>>>>>>>>>>>>ng.>.>>>>>>>>>>>>>>>>>.>.>.>.>.>.>r.>>n

target:     <även jag läste den och fick tillåtelse att göra illustrationer på de breda marginalerna.>________________________
prediction: <även jag läste den och fick tillåtelse att göra illustrationer på de breda margilen.>.>.>.>ernan.>.>.>>>>>>>>>>>>>>>>>>ena.>>>>>>>>>>>.>.>.>ganana.> .>.>>.>

target:     <låt dem veta att vi vet vad som pågår.>__________________________________________________________________________
prediction: <låt dem veta att vi var efter på som våra taga pågår.>>.>>.>>.>>.>>.>>.>>.>>.>.>.>>.>.>.>.>.>>>.>.>>.>>>>>>>>.>.>>>>>>>>>>>>>>>>>>>>>>.>.>s.>.>.>.>.>.>.>>ng

target:     <jag ska lära sig att hålla dig tyst, när jag vill sova.>_________________________________________________________
prediction: <jag ska lära sig att hålla dig tyst, när jag vill sovda.>>.>>.>>.>>.>>.>.>>.>>.>.>>.>>.>.>.>>>.>.>.>>>>>>>>>>>>>>>>>>>>f.>>>>>>>>>>>sssssssss.>.>.>.>.>.>>>s
#+end_src


* References
#+print_bibliography: 
